### ISSUE TITLE
Application form for stores

### ISSUE THREAD

**Issue by pannkotsky** [pannkotsky/holo-apollo#73]
https://marvelapp.com/dbefe04/screen/49979255

**Comment by irasober** [comment]
**Design advices:**

**1.** "Add Photo"(Загрузить фото) button - styles:
Normal - #4CAAD0
Hover - #346D84
Disabled - #E3E3E3
(icon+text)


**2.** Icons and images you can find here: https://drive.google.com/open?id=15BY1nnfwb6UXsSACa7OHX0qQu5rmIlB-

**3.** Information for data base, you can find here: https://docs.google.com/spreadsheets/d/11drCgAW9moeYP5l3nr6oUWl01-O3k0S_XsiSYent4u8/edit?usp=sharing
